- name: "GHOST Busters 2015"
  hosts: haunted-mansions
  sudo: no
  vars:
    - local_home: "{{ lookup('env','HOME') }}"
    - local_log_dir: "{{ local_home }}/gb15-logs"
    - remote_log_dir: "/var/log/ghostbusters15"
#  tasks:
#    - debug: var=inventory_hostname
  roles:
    - { role: seeker ,   tags: [ 'seeker' ] }
    - { role: buster ,   tags: [ 'buster' ] }
    - { role: vacuumer , tags: [ 'vacuumer' ] }
    - { role: seeker ,   tags: [ 'seeker' ] }

